// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: snowflake.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IDService_Generate_FullMethodName    = "/id_service.IDService/Generate"
	IDService_GenerateIDs_FullMethodName = "/id_service.IDService/GenerateIDs"
)

// IDServiceClient is the client API for IDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IDServiceClient interface {
	Generate(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*IDResponse, error)
	GenerateIDs(ctx context.Context, in *IDsRequest, opts ...grpc.CallOption) (*IDsResponse, error)
}

type iDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIDServiceClient(cc grpc.ClientConnInterface) IDServiceClient {
	return &iDServiceClient{cc}
}

func (c *iDServiceClient) Generate(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, IDService_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iDServiceClient) GenerateIDs(ctx context.Context, in *IDsRequest, opts ...grpc.CallOption) (*IDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDsResponse)
	err := c.cc.Invoke(ctx, IDService_GenerateIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IDServiceServer is the server API for IDService service.
// All implementations must embed UnimplementedIDServiceServer
// for forward compatibility.
type IDServiceServer interface {
	Generate(context.Context, *IDRequest) (*IDResponse, error)
	GenerateIDs(context.Context, *IDsRequest) (*IDsResponse, error)
	mustEmbedUnimplementedIDServiceServer()
}

// UnimplementedIDServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIDServiceServer struct{}

func (UnimplementedIDServiceServer) Generate(context.Context, *IDRequest) (*IDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedIDServiceServer) GenerateIDs(context.Context, *IDsRequest) (*IDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateIDs not implemented")
}
func (UnimplementedIDServiceServer) mustEmbedUnimplementedIDServiceServer() {}
func (UnimplementedIDServiceServer) testEmbeddedByValue()                   {}

// UnsafeIDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IDServiceServer will
// result in compilation errors.
type UnsafeIDServiceServer interface {
	mustEmbedUnimplementedIDServiceServer()
}

func RegisterIDServiceServer(s grpc.ServiceRegistrar, srv IDServiceServer) {
	// If the following call pancis, it indicates UnimplementedIDServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IDService_ServiceDesc, srv)
}

func _IDService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IDService_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDServiceServer).Generate(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IDService_GenerateIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDServiceServer).GenerateIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IDService_GenerateIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDServiceServer).GenerateIDs(ctx, req.(*IDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IDService_ServiceDesc is the grpc.ServiceDesc for IDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "id_service.IDService",
	HandlerType: (*IDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _IDService_Generate_Handler,
		},
		{
			MethodName: "GenerateIDs",
			Handler:    _IDService_GenerateIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snowflake.proto",
}
