// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: snowflake.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_snowflake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snowflake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_snowflake_proto_rawDescGZIP(), []int{0}
}

type IDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDsRequest) Reset() {
	*x = IDsRequest{}
	mi := &file_snowflake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDsRequest) ProtoMessage() {}

func (x *IDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snowflake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDsRequest.ProtoReflect.Descriptor instead.
func (*IDsRequest) Descriptor() ([]byte, []int) {
	return file_snowflake_proto_rawDescGZIP(), []int{1}
}

func (x *IDsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type IDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDResponse) Reset() {
	*x = IDResponse{}
	mi := &file_snowflake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDResponse) ProtoMessage() {}

func (x *IDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snowflake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDResponse.ProtoReflect.Descriptor instead.
func (*IDResponse) Descriptor() ([]byte, []int) {
	return file_snowflake_proto_rawDescGZIP(), []int{2}
}

func (x *IDResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	DurationMs    int64                  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDsResponse) Reset() {
	*x = IDsResponse{}
	mi := &file_snowflake_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDsResponse) ProtoMessage() {}

func (x *IDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snowflake_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDsResponse.ProtoReflect.Descriptor instead.
func (*IDsResponse) Descriptor() ([]byte, []int) {
	return file_snowflake_proto_rawDescGZIP(), []int{3}
}

func (x *IDsResponse) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *IDsResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_snowflake_proto protoreflect.FileDescriptor

const file_snowflake_proto_rawDesc = "" +
	"\n" +
	"\x0fsnowflake.proto\x12\n" +
	"id_service\"\v\n" +
	"\tIDRequest\"\"\n" +
	"\n" +
	"IDsRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\x1c\n" +
	"\n" +
	"IDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"@\n" +
	"\vIDsResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x03R\n" +
	"durationMs2\x86\x01\n" +
	"\tIDService\x129\n" +
	"\bGenerate\x12\x15.id_service.IDRequest\x1a\x16.id_service.IDResponse\x12>\n" +
	"\vGenerateIDs\x12\x16.id_service.IDsRequest\x1a\x17.id_service.IDsResponseB Z\x1esnowflake/internal/proto;protob\x06proto3"

var (
	file_snowflake_proto_rawDescOnce sync.Once
	file_snowflake_proto_rawDescData []byte
)

func file_snowflake_proto_rawDescGZIP() []byte {
	file_snowflake_proto_rawDescOnce.Do(func() {
		file_snowflake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snowflake_proto_rawDesc), len(file_snowflake_proto_rawDesc)))
	})
	return file_snowflake_proto_rawDescData
}

var file_snowflake_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_snowflake_proto_goTypes = []any{
	(*IDRequest)(nil),   // 0: id_service.IDRequest
	(*IDsRequest)(nil),  // 1: id_service.IDsRequest
	(*IDResponse)(nil),  // 2: id_service.IDResponse
	(*IDsResponse)(nil), // 3: id_service.IDsResponse
}
var file_snowflake_proto_depIdxs = []int32{
	0, // 0: id_service.IDService.Generate:input_type -> id_service.IDRequest
	1, // 1: id_service.IDService.GenerateIDs:input_type -> id_service.IDsRequest
	2, // 2: id_service.IDService.Generate:output_type -> id_service.IDResponse
	3, // 3: id_service.IDService.GenerateIDs:output_type -> id_service.IDsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_snowflake_proto_init() }
func file_snowflake_proto_init() {
	if File_snowflake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snowflake_proto_rawDesc), len(file_snowflake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snowflake_proto_goTypes,
		DependencyIndexes: file_snowflake_proto_depIdxs,
		MessageInfos:      file_snowflake_proto_msgTypes,
	}.Build()
	File_snowflake_proto = out.File
	file_snowflake_proto_goTypes = nil
	file_snowflake_proto_depIdxs = nil
}
